# Generated by Django 3.2.9 on 2022-04-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video', models.FileField(upload_to='video/%y')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('youtube_url', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
